name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: ./durgaprasad162/durgaprasad162/action.yml
        with:
          github_user_name: durgaprasad162
          outputs: |
            github-contribution-grid-snake.svg?palette=github-dark&color_snake=#00ff00

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
